CREATE SCHEMA "sport";

CREATE TABLE "sport"."client" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(5) NOT NULL,
  "name" varchar(100) NOT NULL,
  "domain_local" varchar NOT NULL,
  "domain_production" varchar NOT NULL,
  "whatsapp_number" varchar(13) NOT NULL,
  "whatsapp_message" text NOT NULL,
  "whatsapp_link" text NOT NULL,
  "fb_link" text NOT NULL,
  "ig_link" text NOT NULL,
  "path_logo" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "sport"."client_cms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int NOT NULL,
  "hero_section" text NOT NULL,
  "about_section" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "sport"."news" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int NOT NULL,
  "code" varchar(32) NOT NULL,
  "title" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "path_photo" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "sport"."class" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int NOT NULL,
  "code" varchar(32) NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "sport"."class_package" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "code" varchar(32) NOT NULL,
  "name" varchar(100) NOT NULL,
  "price" varchar(100) NOT NULL,
  "customer_type" int NOT NULL,
  "type" int NOT NULL,
  "description" text NOT NULL,
  "path_photo" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "deleted_at" timestamp
);

COMMENT ON COLUMN "sport"."client_cms"."hero_section" IS '{"title":"Nan","path_bg":"Nan"}';

COMMENT ON COLUMN "sport"."client_cms"."about_section" IS '{"title":"Nan","description":"Nan","path_photo":"Nan"}';

COMMENT ON COLUMN "sport"."news"."code" IS 'uuid generate';

COMMENT ON COLUMN "sport"."class"."code" IS 'uuid generate';

COMMENT ON COLUMN "sport"."class_package"."code" IS 'uuid generate';

COMMENT ON COLUMN "sport"."class_package"."customer_type" IS '1="member",2="non member"';

COMMENT ON COLUMN "sport"."class_package"."type" IS '1="visit",2="day",3="week",4="month",5="unlimeted"';

ALTER TABLE "sport"."client_cms" ADD FOREIGN KEY ("client_id") REFERENCES "sport"."client" ("id");

ALTER TABLE "sport"."news" ADD FOREIGN KEY ("client_id") REFERENCES "sport"."client" ("id");

ALTER TABLE "sport"."class" ADD FOREIGN KEY ("client_id") REFERENCES "sport"."client" ("id");

ALTER TABLE "sport"."class_package" ADD FOREIGN KEY ("class_id") REFERENCES "sport"."class" ("id");
