// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type SportClass struct {
	ID       int32 `json:"id"`
	ClientID int32 `json:"client_id"`
	// uuid generate
	Code        string       `json:"code"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type SportClassPackage struct {
	ID      int32 `json:"id"`
	ClassID int32 `json:"class_id"`
	// uuid generate
	Code  string `json:"code"`
	Name  string `json:"name"`
	Price string `json:"price"`
	// 1="member",2="non member"
	CustomerType int32 `json:"customer_type"`
	// 1="visit",2="day",3="week",4="month",5="unlimeted"
	Type        int32        `json:"type"`
	Description string       `json:"description"`
	PathPhoto   string       `json:"path_photo"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type SportClient struct {
	ID               int32        `json:"id"`
	Code             string       `json:"code"`
	Name             string       `json:"name"`
	DomainLocal      string       `json:"domain_local"`
	DomainProduction string       `json:"domain_production"`
	WhatsappNumber   string       `json:"whatsapp_number"`
	WhatsappMessage  string       `json:"whatsapp_message"`
	WhatsappLink     string       `json:"whatsapp_link"`
	FbLink           string       `json:"fb_link"`
	IgLink           string       `json:"ig_link"`
	PathLogo         string       `json:"path_logo"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
}

type SportClientCm struct {
	ID       int32 `json:"id"`
	ClientID int32 `json:"client_id"`
	// {"title":"Nan","path_bg":"Nan"}
	HeroSection string `json:"hero_section"`
	// {"title":"Nan","description":"Nan","path_photo":"Nan"}
	AboutSection string       `json:"about_section"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type SportNews struct {
	ID       int32 `json:"id"`
	ClientID int32 `json:"client_id"`
	// uuid generate
	Code        string       `json:"code"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	PathPhoto   string       `json:"path_photo"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}
